# Generated by Django 3.1 on 2020-08-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=10)),
                ('koState', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInfo',
            fields=[
                ('mID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mName', models.CharField(max_length=10)),
                ('mType', models.CharField(max_length=10)),
                ('price1', models.FloatField()),
                ('price2', models.FloatField()),
                ('price3', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('safetyType', models.IntegerField()),
                ('outType', models.IntegerField()),
                ('shelfLife', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('moID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('oDate', models.DateField()),
                ('aDate', models.DateField()),
                ('moState', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moID', models.CharField(max_length=10)),
                ('mID', models.CharField(max_length=10)),
                ('mName', models.CharField(max_length=10)),
                ('arrival', models.DateField()),
                ('stock', models.IntegerField()),
                ('mState', models.IntegerField()),
            ],
            options={
                'unique_together': {('moID', 'mID', 'mState')},
            },
        ),
        migrations.CreateModel(
            name='MaterialOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('mID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.materialinfo')),
                ('moID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.materialorder')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('mID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.materialinfo')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.kitchenorder')),
            ],
        ),
    ]
